version: '3.7'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./python/Dockerfile
    environment:
      PRODUCTION: "False"
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - "80:8000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django

volumes:
  db: